### ISSUE TITLE
Which version of yarn

### ISSUE THREAD

**Issue by ramandhingra** [NiGhTTraX/ts-monorepo#148]
Hi

Which version of yarn do you recommend to use while installing the node modules for this monorepo-based project. 

Right now, I am using the Classic Stable 1.22.15 and it is giving me errors. There are workarounds stated in this link but still not successful:
https://github.com/yarnpkg/yarn/issues/7807

yarn development is confusing. Here: https://github.com/yarnpkg
they say (yarn branch) 1.x is frozen and bug fixes happen in 'berry branch' whose version is 3.x.

Here, they recommend using the 1.22.15 (classic stable) and at the same time they state that the latest 'rc' is 3.2.0 (berry branch)
https://classic.yarnpkg.com/lang/en/docs/install/#debian-stable

Pl. guide which yarn to use?

What do you prefer: yarn workspaces or npm 7 worksapces?

Thanks

**Comment by NiGhTTraX** [comment]
Hey @ramandhingra, I've only encountered the issue you linked when running `yarn add` inside a monorepo. My workaround has always been specifying the new version in `package.json` and simply running `yarn`.

I prefer and use yarn workspaces. [The tests for this repo run latest yarn 1.22.17.](https://github.com/NiGhTTraX/ts-monorepo/runs/4357115595?check_suite_focus=true#step:4:4)

**Comment by ramandhingra** [comment]
Hi @NiGhTTraX  I decided to go with the pnpm workspaces. pnpm is very fast. The setup is very easy, Unlike yarn, no need to do workarounds, no errors when installing the dependencies.

I recommend you create a branch for pnpm, just like you did for npm7.

Thanks for your reply.
