### ISSUE TITLE
"Experimental support for decorators is a feature that is subject to change in a future release"

### ISSUE THREAD

**Issue by RoyLeibo** [NiGhTTraX/ts-monorepo#151]
Hi,
While trying to setup a monorepo project, using the exact configuration as in this project, I cannot compile it following this error.
The "experimentalDecorators" is set to true in the root tsconfig.json and for some reason the compiler ignores it.
Do you have any idea how to solve it?

**Comment by NiGhTTraX** [comment]
Hey @RoyLeibo, can you provide some more context? Where and when does this error happen? Googling the message returns [VSCode  quirks](https://stackoverflow.com/questions/38271273/experimental-decorators-warning-in-typescript-compilation) for me.
