### ISSUE TITLE
Getting build error in examples/cra

### ISSUE THREAD

**Issue by matty-roses** [NiGhTTraX/ts-monorepo#169]
The following changes are being made to your tsconfig.json file:
  - compilerOptions.paths must not be set (aliased imports are not supported)
  
  Not sure what is causing this, I'm fairly new to the toolchain.
  
 The commands run are just 
 `yarn install`
 `yarn build`

**Comment by NiGhTTraX** [comment]
Hey @matty-roses, does it actually throw an error, or is it just a warning?

CRA doesn't officially support path aliases (the mechanism used to make this monorepo template work) and when it sees them in a `tsconfig.json` it prints that warning and tries to remove them. However, if the aliases are defined in an inherited config (as is the case in the [example](https://github.com/NiGhTTraX/ts-monorepo/blob/5a239ad7fd3ab9c2b41e8ee7abadcff1aa1259fc/examples/cra/tsconfig.json#L2)), it won't actually remove them, and just print the warning and successfully build.
