### ISSUE TITLE
 How would you add aliases in each of the packages

### ISSUE THREAD

**Issue by gpolanco** [NiGhTTraX/ts-monorepo#197]
I would like to add aliases in the applications.

For example

"~/components/Alert"

But adding the paths property in tsconfig.json would stop the autocompletion between packages from working.

Any idea how I could do it?

**Comment by NiGhTTraX** [comment]
Hey @gpolanco, check out the [cra example](https://github.com/NiGhTTraX/ts-monorepo/blob/1a7ae3227b29fcf24f81da8a75b00aec7e73c0fe/examples/cra/tsconfig.paths.json). You have to duplicate the monorepo aliases when you add package aliases, since config inheritance doesn't merge them, sadly.

**Comment by gpolanco** [comment]
Thanks, @NiGhTTraX    for your answer. 

I am creating a monorepo using `pnpm` with `nextjs` project and component libraries

It has worked for me to add the `paths` property in the `tsconfig.json` of the package. It didn't work for me because I needed to add the property `"baseUrl": ".",` XD

Thank you very much for your tutorials, they have been very helpful.

Greetings!

**Comment by NiGhTTraX** [comment]
Glad to hear you solved it!
