### ISSUE TITLE
add rollup example

### ISSUE THREAD

**Issue by wellrus** [NiGhTTraX/ts-monorepo#21]
We found example for webpack. But how about example for rollup?

**Comment by NiGhTTraX** [comment]
Hey @wellrus. I added a simple [Rollup example](https://github.com/NiGhTTraX/ts-monorepo/tree/c52a6e68e61827ba4d1566966634a414416a5931/examples/rollup) which seems to be working for me. I'm not 100% sure about it, especially the [`external` config](https://github.com/NiGhTTraX/ts-monorepo/blob/c52a6e68e61827ba4d1566966634a414416a5931/examples/rollup/rollup.config.js#L8), so any feedback is appreciated.
