### ISSUE TITLE
How to enable autocomplete

### ISSUE THREAD

**Issue by zerkalica** [NiGhTTraX/ts-monorepo#22]
Autocomplete in vscode not working without import. I try master and project-references branch. Have you explored the possibility to enable autocomplete?

![image](https://user-images.githubusercontent.com/274786/93710008-b7068c00-fb4b-11ea-850e-6fb6365f1b65.png)

**Comment by NiGhTTraX** [comment]
Hey @zerkalica, unfortunately I don't use VS Code (I use WebStorm/IntelliJ instead) so I don't know what's needed to make it work. Maybe it doesn't like the presence of multiple `tsconfig.json` configs and the inheritance between them. If your project permits it maybe you could try having a single config in the root.

**Comment by ekr3peeK** [comment]
Hey @zerkalica ! I am struggling with a simmilar issue inside a monorepo, did you manage to pinpoin the problem and solve it somehow?
