### ISSUE TITLE
Missing documentation or not possible?

### ISSUE THREAD

**Issue by deanhiller** [NiGhTTraX/ts-monorepo#241]
This repo template is great and 

1. I went into examples/nestjs 
2. ran pnpm run start:dev
3. Changed meaningOfLife = 44; instead of 42
4. refreshed browser page but my browser still displays 42 not 44 after my change.

Is there some kind of constant compile thing I am missing so developers can work in the monorepo live.

thanks,
Dean

**Comment by NiGhTTraX** [comment]
Hey @deanhiller, thanks for reporting this! After some debugging, it seems that if `packages/foo` has build output (the `dist` folder), Nest will use that and not the source code, even though the watcher will be triggered on changes. If you delete `foo/dist` the problem goes away. I've reported this at https://github.com/nestjs/nest/issues/9577.
