### ISSUE TITLE
How it works with vite & Styled Components

### ISSUE THREAD

**Issue by FredericoGauz** [NiGhTTraX/ts-monorepo#285]
Hi,

I was looking at this template and it seems to be just what I have looking for quite a some time, I have a medium sized project that is set on yarn workspaces but have a few issues with code sharing (like not being able to automatically find a dependency when used for the first time, i.e. I have to manually write it's path once in that package) and sometimes quite a few very cryptic errors regarding having different versions of (typescript for example) on different packages or errors in finding those same dependencies.

But before moving everything to this project, I would like to ask first if anyone has used this setup with **vite** and **styled components** (the version with babel support) before, and if so, if that worked.

I have had particular difficult with using styled components babel support in components imported from another library (internal library in the project).

Thanks is advance!

**Comment by NiGhTTraX** [comment]
Hey @FredericoGauz, I just added a [Vite example](https://github.com/NiGhTTraX/ts-monorepo/tree/ffd6d1759707fa497dd97917ef46e87402978513#vite).

>  styled components (the version with babel support)

Regarding this, can you clarify what babel support means here? Is it [this](https://styled-components.com/docs/tooling#babel-plugin)? Perhaps the [babel-example](https://github.com/NiGhTTraX/ts-monorepo/blob/9cfb14bc6500f2be519ae685deb3be6cdf303552/apps/jest-babel/babel.config.js) is what you need?
