### ISSUE TITLE
How should I go about using it, like copying the code? I didn't see the instructions for use.

### ISSUE THREAD

**Issue by kongchenglc** [NiGhTTraX/ts-monorepo#286]

**Comment by NiGhTTraX** [comment]
You could clone/fork/use this template and bring in your own code, while removing the examples you don't need, or you could pick the necessary configs from it and apply them to your own project. Check the articles in the [docs section](https://github.com/NiGhTTraX/ts-monorepo/tree/7b0ab7b9d0f84cf3837f954030cd46a83dc2b5a0#docs) to understand how you can start from scratch.
