### ISSUE TITLE
How to make find all references working?

### ISSUE THREAD

**Issue by RemVN** [NiGhTTraX/ts-monorepo#304]
Auto-import and go to definition work fine for me, but I couldn't find a way to make find all references work. Renaming will not work either 
![image](https://user-images.githubusercontent.com/34063162/210134961-b08a3fa4-9be4-4b06-bbe2-82fc5eb62c60.png)

no reference on this file
![image](https://user-images.githubusercontent.com/34063162/210135071-131c4822-7c84-4685-b322-b175f14b0a91.png)

**Comment by NiGhTTraX** [comment]
Hmm, it does seem like VS Code 1.74.2 doesn't find references correctly. After opening some files where that export is used, VS Code starts showing them up:

<img width="633" alt="image" src="https://user-images.githubusercontent.com/485061/210445445-a1cacba1-d236-4be0-8a98-ef2f0608d929.png">

Maybe you could let the team at https://github.com/microsoft/vscode know about this?

----

For reference (pun intended) WebStorm/IntelliJ work fine:

<img width="1042" alt="image" src="https://user-images.githubusercontent.com/485061/210444904-bdc71f85-8570-4071-8f15-77f82e9d0261.png">

**Comment by RemVN** [comment]
Thanks for your help.

I managed to fix this by add reference to root tsconfig

![image](https://user-images.githubusercontent.com/34063162/210466857-e00191ae-4b2c-4c25-86b0-b47cd75da6d1.png)

and some options in lib repo

![image](https://user-images.githubusercontent.com/34063162/210466900-58980181-dac9-4c34-8100-6f0b1909b72a.png)

Now it works as excepted

![image](https://user-images.githubusercontent.com/34063162/210466966-70aca74e-bb1f-4b1d-9e98-de91582877ab.png)
