### ISSUE TITLE
How can I handle css/less in @nighttrax/components

### ISSUE THREAD

**Issue by uuuhs** [NiGhTTraX/ts-monorepo#321]
Dear

When I run `pnpm build` in the @nighttrax/components directory, I find that my css files are not packaged in the dist directory. Any suggestions if I want to package this project as a component library

**Comment by NiGhTTraX** [comment]
Hey @uuuhs, the exact setup for importing LESS/CSS (or any other static assets) is up to you, but will most likely involve a bundler (webpack, rollup etc.). As such, it's a bit out of scope for this repo, but I'll note that whatever setup you choose, you will most likely have to replicate it for any consumer of the shared package if you want to use path aliases for hot reload and jump to definition.
