### ISSUE TITLE
This problem must appear when using react-router-dom@6 

### ISSUE THREAD

**Issue by cjcj5438** [NiGhTTraX/ts-monorepo#329]
The problem is shown in Fig

![image](https://github.com/NiGhTTraX/ts-monorepo/assets/23037115/8cda7cce-3818-4121-9356-80b48f65d49b)

**Comment by NiGhTTraX** [comment]
See https://github.com/remix-run/react-router/issues/10787.

P.S.: a non English screenshot is very little to go on when seeking help.
