### ISSUE TITLE
Problems of adding Sveltekit in apps

### ISSUE THREAD

**Issue by Jedliu** [NiGhTTraX/ts-monorepo#332]
Hi, thank you for your contribution to this repo. It's the most elaborate pnpm monorepo I've found. The articles you wrote are very helpful.

I'm trying to add Sveltekit to the apps folder. I'd like to develop a package working for both the Nestjs and Sveltekit. I tried to call the package `@nighttrax/foo` in `apps/sveltekit/src/routes/+page.svelte`. You could find the [cloned repo here](https://github.com/Jedliu/ts-monorepo). 

**Here are the problems I'm having:**

1. Run the dev of Sveltekit app by `pnpm --filter=sveltekit dev`.

2. Without building the package `@nighttrax/foo`, there is an error.

```
Failed to resolve entry for package "@nighttrax/foo".
```
<img width="1074" alt="iShot_2024-01-25_12 57 59" src="https://github.com/NiGhTTraX/ts-monorepo/assets/771703/852e2458-3bb7-4727-98c2-fbc33938b310">

3. After building the package `@nighttrax/foo`, there is another error.

```
ReferenceError: exports TS Tot uer meu
```
<img width="1072" alt="iShot_2024-01-25_12 59 07" src="https://github.com/NiGhTTraX/ts-monorepo/assets/771703/bc94a1db-093b-4240-b6c0-09598fd62242">

Would you please advise how to make it work? Thank you!

**Comment by NiGhTTraX** [comment]
Hey @Jedliu, I don't have any experience with Svelte, but it seems like Sveltekit has its own config for aliases https://kit.svelte.dev/docs/configuration#alias. Try duplicating the aliases from the [main tsconfig](https://github.com/NiGhTTraX/ts-monorepo/blob/70df0b2837f453b9d81b05f854c3b0724ab41b67/tsconfig.json#L6-L9) there.

**Comment by Jedliu** [comment]
Thanks, I will look into this.
