### ISSUE TITLE
Cannot find module '@nighttrax/foo' or its corre…

### ISSUE THREAD

**Issue by men232** [NiGhTTraX/ts-monorepo#339]
Thank you for your amazing repo, I just tried to set up it for my own needs and failed. Here is what I did:

1. Cloned repo.
2. `pnpm i`
3. `pnpm run build`

```
❯ pnpm run build

> ts-monorepo@ build /Users/andrewl/Downloads/ts-monorepo-master
> pnpm run -r build

Scope: 13 of 14 workspace projects
packages/bar build$ pnpm run clean && pnpm run compile
│ > @nighttrax/bar@1.0.0 clean /Users/andrewl/Downloads/ts-monorepo-master/packages/…
│ > rimraf ./dist
│ > @nighttrax/bar@1.0.0 compile /Users/andrewl/Downloads/ts-monorepo-master/package…
│ > tsc -p tsconfig.build.json
│ src/index.ts(1,31): error TS2307: Cannot find module '@nighttrax/foo' or its corre…
│  ELIFECYCLE  Command failed with exit code 1.
└─ Failed in 711ms at /Users/andrewl/Downloads/ts-monorepo-master/packages/bar
packages/foo build$ pnpm run clean && pnpm run compile
│ > @nighttrax/foo@1.0.0 clean /Users/andrewl/Downloads/ts-monorepo-master/packages/…
│ > rimraf ./dist
│ > @nighttrax/foo@1.0.0 compile /Users/andrewl/Downloads/ts-monorepo-master/package…
│ > tsc -p tsconfig.build.json
└─ Done in 696ms
```

Please, let me know if I do smt wrong.
I'm trying to launch demo under mac.

P.S. Maybe I mess in node-linker configuration?

**Comment by NiGhTTraX** [comment]
Hi @men232, thanks for reporting this. There seems to be an issue with pnpm@9 that breaks the topological order when running scripts recursively. I've submitted https://github.com/pnpm/pnpm/issues/7997.

In the mean time, please use pnpm@8. I've tested `8.15.7` locally and it works as expected.

**Comment by NiGhTTraX** [comment]
@men232 this is fixed in the latest master.
