### ISSUE TITLE
Problem with using expec

### ISSUE THREAD

**Issue by henriqueweiand** [NiGhTTraX/ts-monorepo#45]
Applying tests in particular with toBeInTheDocument I'm having the following problem. I am not sure if it is for some reason that monorepo is unable to locate the lib of jest so that he can identify such a method
![Screen Shot 2021-02-03 at 23 11 24](https://user-images.githubusercontent.com/6539492/106890850-ab65cd00-66c8-11eb-8452-141fab522c0f.png)

**Comment by NiGhTTraX** [comment]
Hey @henriqueweiand. I'm assuming that `toBeInDocument` is coming from [jest-dom](https://github.com/testing-library/jest-dom). Are you following their [setup instructions](https://github.com/testing-library/jest-dom#with-typescript)? You can add your test setup file to the root `tsconfig.json` of the monorepo (that all others inherit from) or you can add it inside a specific package.

**Comment by henriqueweiand** [comment]
I followed the jest configuration tips and it really worked! thank you
