### ISSUE TITLE
Rollup example declaration file not generated

### ISSUE THREAD

**Issue by gmpetrov** [NiGhTTraX/ts-monorepo#46]
Hello i just noticed that declaration files are not generated when building the rollup example. 

You can fix that with an update to the rollup config https://github.com/rollup/plugins/issues/61#issuecomment-597090769

**Comment by NiGhTTraX** [comment]
Hey @gmpetrov, this repo is not meant to cover all the common cases of TS development, but just focus on the monorepo structure. The config files are kept to a minimum as not everyone has the same requirements.
