### ISSUE TITLE
next and next-transpile-modules

### ISSUE THREAD

**Issue by MythicManiac** [NiGhTTraX/ts-monorepo#54]
Currently this template has a nextjs 9 example project, using `next-transpile-modules` 3.3.0 to handle shared packages. For reference, as of writing this `next-transpile-modules` is at version 6.4.0, and next is version 10.

As I described in the nextjs issue here https://github.com/vercel/next.js/issues/5666#issuecomment-812979574, the `next-transpile-modules` changed their module resolution to use [enhanced-resolve](https://www.npmjs.com/package/next-transpile-modules) between the versions 3 and 4, which seemingly broke the usecase found in this repo.

As also suggested in that thread, I managed to work around this issue in my own project with the following next.config.js:
```js
module.exports = {
  webpack: (config) => {
    config.module.rules.forEach((rule) => {
      if (rule.test && rule.test.toString().includes("tsx|ts")) {
        rule.include = [
          ...rule.include,
          // eslint-disable-next-line @typescript-eslint/no-var-requires
          require("path").join(__dirname, "../../packages"),
        ];
      }
    });
    return config;
  },
};
```

So far I'm unsure if there are any caveats to this approach as compared to `next-transpile-modules`. Either way, it might make sense to update the template to use something that does not break with latest versions of the packages involved.

**Comment by NiGhTTraX** [comment]
Thanks for reporting this, @MythicManiac! I've updated the [example](https://github.com/NiGhTTraX/ts-monorepo/blob/08e9c70b2af8493e6b8700fa12409198c62248c1/examples/nextjs/next.config.js) to use the same override as CRA. Using `include = undefined; exclude = /node_modules/` will limit the scope of the compilation to only the files included in you app and produce smaller bundles (56kb vs 62kb in this example)
