### ISSUE TITLE
examples/cra fails to build on fresh clone, with `Delete 'CRLF'  prettier/prettier`

### ISSUE THREAD

**Issue by efokschaner** [NiGhTTraX/ts-monorepo#63]
I ran in to a build failure after doing the following on a fresh clone:
```
# npm version >=7 supports workspaces like yarn
npm install
npm run build
```
The error message:
```
lerna ERR! yarn run build exited 1 in '@nighttrax/cra-example'
lerna ERR! yarn run build stdout:
yarn run v1.22.10
$ cross-env SKIP_PREFLIGHT_CHECK=true react-app-rewired build
Creating an optimized production build...
Failed to compile.

src\index.tsx
  Line 1:27:   Delete `CRLF`  prettier/prettier
  ...
```
I am on Windows which is definitely relevant to this problem.

The prettier eslint plugin and rules appear to come from `https://github.com/NiGhTTraX/eslint-config/blob/master/packages/base/index.js#L24`

I'm not sure how you prefer to address this, but here are some ideas:
- Recommend Windows users set their git settings to not use the default of crlf.
- Have the instructions or the build command itself include a `prettier --write` at some step for either this example or the entire repo to fix up line endings and other stuff.
- Customize the eslint rule for prettier to include `"endOfLine":"auto"` for either this example or the whole repo.

Thanks!

**Comment by NiGhTTraX** [comment]
Hey @efokschaner, I've disabled ESLint in the CRA example 26bfd4a836a4c92bea6b1ce76002a64767d34f69.

**Comment by efokschaner** [comment]
Thanks for dealing with this!

**Comment by efokschaner** [comment]
With https://github.com/NiGhTTraX/ts-monorepo/commit/26bfd4a836a4c92bea6b1ce76002a64767d34f69 , I no longer have the issue!
