### ISSUE TITLE
Awesome repo - code splitting suggestion

### ISSUE THREAD

**Issue by R-Bower** [NiGhTTraX/ts-monorepo#64]
This has to be the best Typescript/Next/Lerna monorepo I've seen yet.  I've been searching for weeks for an optimal configuration.  My requirements were:
- ESLint applied to all sub-projects from root configuration.
- Typescript support.
- Hot reloading adjacent packages in the repo.  
- Optional publishing support.
- Code splitting.

This checks all of the boxes except for the last one, but it's a simple fix.

I'm primarily concerned with the NextJS package and importing from other libs in the monorepo.  To reproduce my issue, do the following:
1. `yarn build` and observe the first load JS bundle size for the NextJS build (should be around 59KB)
2. in `packages/components`, add `react-select` as a dependency.
3. add `packages/components/src/select.tsx` with the following code:
```
import React from "react";
import Select from "react-select";

export function MySelect(): JSX.Element {
  return <Select />;
}
```
4. update `packages/components/src/index.tsx`:
```
export * from "./button";
export * from "./select";
```
5. `yarn build` at the root and observe the first load JS bundle size for the NextJS build (should now be somewhere around 86KB).  This isn't ideal, as we've simply added a component that we're not using to another package in the repo.  

Ideally, only the components that are imported should be included in the bundle.

To fix: 
1. Edit the root tsconfig.build.json:
```
module: "esnext"
moduleResolution: "node"
```

Code splitting is only supported in the more recent versions of es.  Also, I had to make some modifications to support proper interface/type detection.  Lmk if you want the details!

Cheers, thanks for the code!

EDIT2:
amended steps.

**Comment by R-Bower** [comment]
Note:
I've also needed to adjust the `moduleResolution` and `module` for my custom packages to work.

**Comment by NiGhTTraX** [comment]
Hey @R-Bower, glad you found the repo useful!

Unfortunately I can't reproduce the problem you describe above — NextJS builds an initial chunk of ~59kb even if I add extra components in `@nighttrax/components`. The `tsconfig.json` for Next already includes `module: esnext` which, like you described, should enable tree shaking.

<details>

<summary>These are the details I made locally, should be in line with your description.</summary>

```diff
Index: packages/components/src/index.tsx
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- packages/components/src/index.tsx	(revision 69f03b3ab2cae462e33b19cb0832842bdbc27c58)
+++ packages/components/src/index.tsx	(date 1620496195760)
@@ -1,1 +1,2 @@
 export * from "./button";
+export * from "./select";
Index: packages/components/package.json
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- packages/components/package.json	(revision 69f03b3ab2cae462e33b19cb0832842bdbc27c58)
+++ packages/components/package.json	(date 1620496156756)
@@ -14,7 +14,8 @@
     "react": "~17.0.0"
   },
   "dependencies": {
-    "@nighttrax/foo": "*"
+    "@nighttrax/foo": "*",
+    "react-select": "~4.3.0"
   },
   "devDependencies": {
     "@types/react": "~17.0.0",
Index: yarn.lock
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- packages/components/src/select.tsx	(date 1620496188135)
+++ packages/components/src/select.tsx	(date 1620496188135)
@@ -0,0 +1,4 @@
+import React from "react";
+import Select from "react-select";
+
+export const MySelect = () => <Select />;
```

</details>

Did I miss anything? Maybe you can create and link a repo or paste a diff with the changes you made to this one, where I can see what's happening?

**Comment by R-Bower** [comment]
@NiGhTTraX  this is very strange.  I've just cloned a fresh build of your repo.  I made the same exact changes and this is the before/after of the next build:
Before:
```
Page                                                           Size     First Load JS
┌ ○ /                                                          329 B          58.7 kB
└ ○ /404                                                       2.23 kB        60.6 kB
+ First Load JS shared by all                                  58.3 kB
  ├ chunks/f6078781a05fe1bcb0902d23dbbb2662c8d200b3.c82024.js  8.91 kB
  ├ chunks/framework.e1680a.js                                 41.8 kB
  ├ chunks/main.a6f36f.js                                      6.26 kB
  ├ chunks/pages/_app.b578c6.js                                626 B
  └ chunks/webpack.50bee0.js                                   751 B
```
after:
```
Page                                                           Size     First Load JS
┌ ○ /                                                          28.1 kB        86.8 kB
└ ○ /404                                                       2.23 kB        60.9 kB
+ First Load JS shared by all                                  58.7 kB
  ├ chunks/f6078781a05fe1bcb0902d23dbbb2662c8d200b3.c82024.js  8.91 kB
  ├ chunks/framework.089748.js                                 42.1 kB
  ├ chunks/main.a6f36f.js                                      6.26 kB
  ├ chunks/pages/_app.b578c6.js                                626 B
  └ chunks/webpack.50bee0.js                                   751 B
```

What OS are you running?  I'm on Ubuntu 20.04.  Not sure if this would change anything but it's worth mentioning.

**Comment by R-Bower** [comment]
```
diff --git a/examples/nextjs/next.config.js b/examples/nextjs/next.config.js
index 8278b43..aaef63d 100644
--- a/examples/nextjs/next.config.js
+++ b/examples/nextjs/next.config.js
@@ -7,6 +7,9 @@ module.exports = {
   // experimental: {
   //   externalDir: true,
   // },
+  future: {
+    webpack5: true,
+  },
   webpack: (config) => {
     // Let Babel compile outside of src/.
     const tsRule = config.module.rules.find(
diff --git a/packages/components/package.json b/packages/components/package.json
index e9baac2..3cddeac 100644
--- a/packages/components/package.json
+++ b/packages/components/package.json
@@ -14,7 +14,8 @@
     "react": "~17.0.0"
   },
   "dependencies": {
-    "@nighttrax/foo": "*"
+    "@nighttrax/foo": "*",
+    "react-select": "^4.3.0"
   },
   "devDependencies": {
     "@types/react": "~17.0.0",
diff --git a/packages/components/src/index.tsx b/packages/components/src/index.tsx
index 98d55ac..2161534 100644
--- a/packages/components/src/index.tsx
+++ b/packages/components/src/index.tsx
@@ -1 +1,2 @@
 export * from "./button";
+export * from "./select";
```

**Comment by NiGhTTraX** [comment]
:facepalm: my apologies, I was looking at the initial chunk, not the one for the `/` route.

I went with your suggestion of enabling webpack 5. Thanks for the help!

**Comment by NiGhTTraX** [comment]
I'm hesitant to add too much config for tree shaking as the best setup can be different depending on project. This repo aims to keep things to a minimum and let everyone customize it to their needs.

The CRA example has the same issue with tree shaking. `sideEffects: false` _could_ improve things, but if you add components that load static assets then you'd need to turn it off or customize it further.

Webpack 5 seems to have better overall behavior, and it will be the new default in the next major of version of Next, so I'm betting on that as the long term solution.

**Comment by R-Bower** [comment]
Fair point.  May want to add a segment in the readme detailing the potential issues.  I actually ran into a compilation error by enabling Webpack 5 while using `styled-components`, which is why I made the suggestion to avoid.  Agreed, Webpack 5 is likely the best long-term solution.

**Comment by NiGhTTraX** [comment]
Thanks for the feedback, @R-Bower. To be on the safe side, I reverted the webpack 5 change fc24f0d4415f32a4f1524641c3b869193101be30 and clarified that tree shaking is left to the user to configure 8deb923bfe2a2c52ac4f3244c88a3ce3dc5d7285.

There shouldn't be anything specific to this monorepo setup that would get in the way of configuring tree shaking, so I hope people can just tailor the config to meet their project's needs.
