### ISSUE TITLE
Importing non "main" modules?

### ISSUE THREAD

**Issue by momsse** [NiGhTTraX/ts-monorepo#68]
Hi @NiGhTTraX,

Thanks for the article and sharing your work 👌

I tried to add an extra `foo/src/demo.ts` module and importing it from `bar/src/index.ts` after adding `files: ["dist"]` on `foo/package.json`. 

```typescript
import demo from "@nighttrax/foo/src/demo";
import demo from "@nighttrax/foo/demo";
```

Both syntaxes ends with `Error: Cannot find module '@nighttrax/foo/[src/]demo`

Is it possible to import non "main" modules (without having to import and export them from the main one)?

All typescript mono repo examples that I found so far showcase the same kind of example of package `a` import module `b`'s single exported main module.

**Comment by NiGhTTraX** [comment]
Hi @momsse, this is answered in #53. The TL;DR is:

- you can add a new path alias before the "main" one, like so:

```js
"paths": {
  // This need to be first, so index imports can be matched by the next alias.
  // You can add or omit the `src` part here, depending on your preference.
  //                                 V
  "@nighttrax/foo/*": ["packages/foo/*"],

  "@nighttrax/*": ["packages/*/src"]
}
```

- doing the above will break publishing, unless you:
  - use the aliases during building as well,
  - publish from within the `dist/` folder, after you've copied your `package.json` there.
- using imports like this makes library APIs more brittle, as changes in the folder structure can break consumers.

**Comment by momsse** [comment]
Thanks you for the help, will try this soon 🙏
