### ISSUE TITLE
No serve/watch scripts?

### ISSUE THREAD

**Issue by harm-less** [NiGhTTraX/ts-monorepo#70]
Hey mate,

I've been using this repo as a starter for my monorepo since a few months and it's working pretty well for the most part. I'm glad the tooling (TS, Lerna, VSCode, e.g.) is working as expected in most important ways.

But am I correct in saying that there's not clear best practice or even implementation in serving and watching the packages?

Harm

**Comment by NiGhTTraX** [comment]
Hey @harm-less. The implementation depends on the kind of package you're building. For instance, [create-react-app](https://github.com/NiGhTTraX/ts-monorepo/tree/0c0744193ec0bdb660a2654268a7bd34b703f200/examples/cra) automatically watches and rebuilds on file changes, even across the monorepo. If you're building server applications then maybe the [ts-node example](https://github.com/NiGhTTraX/ts-monorepo/blob/0c0744193ec0bdb660a2654268a7bd34b703f200/examples/ts-node/package.json#L7) will fit your needs (you can use it in combination with [nodemon](https://www.npmjs.com/package/nodemon) or switch to [ts-node-dev](https://www.npmjs.com/package/ts-node-dev) instead to enable watch mode).

The key to all of those example is the [tsconfig-paths](https://www.npmjs.com/package/tsconfig-paths) package which will make the path aliases work at runtime.

**Comment by harm-less** [comment]
Hey mate,

Thanks for the quick response. But you're completely right. I've been struggling with this since a long time as I was using Parceljs (can recommend for quick development or demos) and next to that Vue. But it wasn't your repo but these techniques that created my problems.

Based on your React example I tried doing the same for my Vue project that was using a package similar to your "foo" package.

For my Vue packages (regular `vue create [projectName]`) I did the following:
1. This is what I added in my TSConfig. This was necessary as the `paths` property is not merged with the ones from the root config file:
```json
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    ...
    "paths": {
      "@wp/*": ["../*/src"],
      "@/*": [
        "src/*"
      ]
    },
    ...
  },
  ...
}

```

2. Then I applied this: https://zaiste.net/programming/vuejs/howtos/howto-include-typescript-tsconfig-paths-webpack-aliases-vuejs/

This works without me having to serve/build the packages 👌 

This is both faster and without the need of having to run multiple scripts simultaneously. 

I don't think this works for my Parceljs demo package as that doesn't use the tsconfig from the package it's in, so I need to to upgrade to Parcel 2 as they claim it can work with the tsconfig with certain steps.

Anyway, thanks for having taken the time to create this repo, it helped me prevent a lot of frustration 😉

**Comment by NiGhTTraX** [comment]
Glad to hear you solved it!

> This was necessary as the paths property is not merged with the ones from the root config file

Yeah, there's an [open request](https://github.com/microsoft/TypeScript/issues/20110) for this in the TypeScript project, but I wouldn't hold my breath for it :)
