### ISSUE TITLE
Can't resolve './styles.module.css'. Do I need extra configuration ?

### ISSUE THREAD

**Issue by MinThuKhant03** [NiGhTTraX/ts-monorepo#80]
I was using a component from "components package" inside monorepo which is a button component. When I run from its own package, it runs with no problem. But if is is used from another package it shows this error.

../components/dist/components/atoms/Test/index.js
Module not found: Can't resolve './styles.module.css' in ...component path.

Any idea that can solve? thank in advance.

**Comment by NiGhTTraX** [comment]
Hey @MinThuKhant03, could you share some example code?
