### ISSUE TITLE
install dependencies with npm install

### ISSUE THREAD

**Issue by Giuseppedes** [NiGhTTraX/ts-monorepo#81]
Thank you for your work. 
I cloned the project for trying it and I found out that dependencies are installed correctly only running `lerna bootstrap` from the root; I get an error when I try to run `npm i` in  'packages/bar' directory.
It tries to download 'foo' dependency from the public npm registry, instead of using the one in the monorepo.

Is there a way to fix this issue and have `npm i` working as well as `lerna bootstrap`?

**Comment by Giuseppedes** [comment]
Can this change be a suitable solution?

`  "dependencies": {
    "@nighttrax/foo": "../foo"
  },`

instead of 

`  "dependencies": {
    "@nighttrax/foo": "^1.0.0"
  },`

in `packages/bar/package.json`

**Comment by NiGhTTraX** [comment]
Hey @Giuseppedes, you need npm 7 for monorepo support, and then running `npm install` in the root will install the dependencies for all the packages.

**Comment by Giuseppedes** [comment]
Oh ok, with npm 7 all the dependencies are placed in the root node_modules and you don't need to run it in each package (even with` lerna bootstrap`), right?

**Comment by NiGhTTraX** [comment]
Correct. npm 7 and yarn don't need lerna.

**Comment by Giuseppedes** [comment]
Cool, thank you!
