### ISSUE TITLE
React cra with testing

### ISSUE THREAD

**Issue by UnrealDoggie** [NiGhTTraX/ts-monorepo#82]
Hi,

The tsconfig-paths works in development but not when running react-app-rewired test.
I am using typescript.
 Cannot find module '@client/package' from 'src/Context.ts'
What should be added to get test to recognize the import module outside of src?

Thanks.

**Comment by NiGhTTraX** [comment]
Hey @UnrealDoggie, you need to use `react-app-rewired` to apply the jest configs from the [jest example](https://github.com/NiGhTTraX/ts-monorepo/tree/55afb7d0eb3854e4dbb133376357f5e6fdc7dfcb#jest).

**Comment by UnrealDoggie** [comment]
Hi @NiGhTTraX,
Oic Thanks.
I specified in the package.json jest config "moduleNameMapper" and that seem to work for the tests.
Is that all right as well?

**Comment by NiGhTTraX** [comment]
Yes, that's perfectly fine!
