### ISSUE TITLE
member variable not found error

### ISSUE THREAD

**Issue by whaqzhzd** [NiGhTTraX/ts-monorepo#86]
step 1 ：export a class in a package
![image](https://user-images.githubusercontent.com/16913061/128001392-89a9fe36-8d86-47b2-b08b-4ee8a1c75a8e.png)
step 2 :  import the exported class in another package，then inherit it in this package
![image](https://user-images.githubusercontent.com/16913061/128002036-e593224f-a548-444a-af19-6858521cd453.png)
step 3 : npm run build 
error will be found at this time

![image](https://user-images.githubusercontent.com/16913061/128001909-baebbdac-de6f-4bc8-93b1-6fb6e8da43ee.png)

what should i do, thank you

**Comment by NiGhTTraX** [comment]
Hey @whaqzhzd, thanks for reporting this. You need to have `declaration: true` in the `tsconfig.build.json`. I've now added it in the latest version of the project since most people would probably want this.

**Comment by whaqzhzd** [comment]
Great thanks
