### ISSUE TITLE
need CI/CD tips with monorepo strategy

### ISSUE THREAD

**Issue by henriqueweiand** [NiGhTTraX/ts-monorepo#91]
I would like one suggestion when applied monorepo strategy.

We go to use this context as example.

![Screen Shot 2021-09-05 at 16 34 41](https://user-images.githubusercontent.com/6539492/132139240-2e3b050c-6e12-47b3-b837-302117f47c64.png)

When I change something in `package/*`, I need on my CI/CD detect all projects those have that specific dependence installed for trigger a deploy as well. 

Existis tip with git commands or others for to help in this case?

**Comment by NiGhTTraX** [comment]
The [`--since`](https://github.com/lerna/lerna/tree/main/core/filter-options#--since-ref) argument for lerna seems promising.

```console
# Made a commit to packages/foo on a new branch from master.
❯ npx lerna ls --since master
lerna notice cli v4.0.0
lerna info versioning independent
lerna notice filter changed since "master"
lerna info Looking for changed packages since master
@nighttrax/bar
@nighttrax/components
@nighttrax/foo
```

It doesn't seem to cover the second workspace in `examples/*`, so maybe I'm missing something, but looks like a good start.

**Comment by NiGhTTraX** [comment]
Turns out `ls` filters private packages (which the ones in `examples/*` are) so you need to use `la` instead :)

```
❯ npx lerna la --since master                                            
lerna notice cli v4.0.0
lerna info versioning independent
lerna notice filter changed since "master"
lerna info Looking for changed packages since master
@nighttrax/cra-example    v1.0.0 examples/cra        (PRIVATE)
@nighttrax/nextjs-example v1.0.0 examples/nextjs     (PRIVATE)
@nighttrax/components     v1.0.0 packages/components
lerna success found 3 packages
```

The `--since` filter is also applicable to the `run` command, so you can use that to e.g. run the tests for the changed packages. Hope this helps!
