### ISSUE TITLE
Using artefacts of ts-monorepo inside a server that might not have the same file system dist folders

### ISSUE THREAD

**Issue by Lilja** [NiGhTTraX/ts-monorepo#92]
Thanks for making this example setup!

I searched through the other issues to try to find others who had tried to find the same question before but I couldn't.
I had a thought about how you would use this in production. I skimmed through the different typescript configuration files and built it on my own machine. What I ended up with was `dist/` files in each `package` folder.
Maybe it's just me and I don't understand how `lerna` works and/or this project goals. But I imagine one of these packages being a server component which I guess would run in some environment with only `node` installed. Which then raises some more question of how you would use it in that context:

* If you have three dist folders inside each package. How would you go about placing it inside a docker container? since `bar` depends on `foo` in these examples. If I just copy `packages/bar/dist` to `/dist/`whatever server I use and then `node /dist/index`, node would surely complain about `@nighttrax/foo` not being found in the files or `node_modules`. I suppose that you could potentially write your docker file so that you would have a structure like the following:
```
/
    bar/
        dist/
           index.js
        node_modules/
    foo/
        dist/
          index.js
        node_modules/
```
(i.e, the exact same structure as the source root, but the source files are removed)

But this solution would require a lot of maintenance in a `Dockerfile` or some shell script.

Am I making sense here? I think that your setup is amazing when the end result of what you need is to publish packages to a npm registry. But if you want to run a server out of one of those packages then it requires a bit more thinking. I mean sure, you could git clone the repository, build it and run `ts-node` on the server you're using but I think that quite inefficient and the source files would still remain at the filesystem.

**Comment by NiGhTTraX** [comment]
Hey, @Lilja. An option that I recommend for running a server out of a monorepo is to bundle it and its dependencies e.g. using [webpack](https://github.com/NiGhTTraX/ts-monorepo#webpack). Then you'll get a single artifact that you can copy in your Docker image and execute.

> (i.e, the exact same structure as the source root, but the source files are removed)
> But this solution would require a lot of maintenance in a Dockerfile or some shell script.

You could use a glob to either copy just the `dist` folders or exclude the `src` folders, though I think this is more trouble than it's worth, compared to using a bundler.

**Comment by Lilja** [comment]
Thanks for the quick reply @NiGhTTraX! I'll check that out.
